// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvQle6EQtzWosZjvTxIsqXfE4vn6vNHBc',
    appId: '1:477566023264:web:80629794db87625cbeb505',
    messagingSenderId: '477566023264',
    projectId: 'myprojects-b3200',
    authDomain: 'myprojects-b3200.firebaseapp.com',
    storageBucket: 'myprojects-b3200.firebasestorage.app',
    measurementId: 'G-DD6761BDY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8irNwtjdeJEmbMBeoRIhDJ47nmdN8r4s',
    appId: '1:477566023264:android:0ecfc0e4e75cea6ebeb505',
    messagingSenderId: '477566023264',
    projectId: 'myprojects-b3200',
    storageBucket: 'myprojects-b3200.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqdBcUN2nRYVH7pVNkyH-ToXXAgA7qYEs',
    appId: '1:477566023264:ios:05a88a8fb953fc9abeb505',
    messagingSenderId: '477566023264',
    projectId: 'myprojects-b3200',
    storageBucket: 'myprojects-b3200.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqdBcUN2nRYVH7pVNkyH-ToXXAgA7qYEs',
    appId: '1:477566023264:ios:05a88a8fb953fc9abeb505',
    messagingSenderId: '477566023264',
    projectId: 'myprojects-b3200',
    storageBucket: 'myprojects-b3200.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvQle6EQtzWosZjvTxIsqXfE4vn6vNHBc',
    appId: '1:477566023264:web:29e55f7ceef6a242beb505',
    messagingSenderId: '477566023264',
    projectId: 'myprojects-b3200',
    authDomain: 'myprojects-b3200.firebaseapp.com',
    storageBucket: 'myprojects-b3200.firebasestorage.app',
    measurementId: 'G-B3HJR6N6ZV',
  );
}
