// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBee4S3pT06qWa6q5xONdQZPOH44_C4PzI',
    appId: '1:433434265166:web:2d26ffbddfa9e1ce0ee51f',
    messagingSenderId: '433434265166',
    projectId: 'authentic-user-dashboard-app',
    authDomain: 'authentic-user-dashboard-app.firebaseapp.com',
    storageBucket: 'authentic-user-dashboard-app.firebasestorage.app',
    measurementId: 'G-GZGRHN9V32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCnxp5nEOCmAeUOdphRBiLw_L_ZPcWe20',
    appId: '1:433434265166:android:f5eb595d5ec6e2550ee51f',
    messagingSenderId: '433434265166',
    projectId: 'authentic-user-dashboard-app',
    storageBucket: 'authentic-user-dashboard-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB088K6KRh059BdRaoCFj2OdhN8ZnzTW4I',
    appId: '1:433434265166:ios:7238933b649e0c900ee51f',
    messagingSenderId: '433434265166',
    projectId: 'authentic-user-dashboard-app',
    storageBucket: 'authentic-user-dashboard-app.firebasestorage.app',
    iosBundleId: 'com.example.week5Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB088K6KRh059BdRaoCFj2OdhN8ZnzTW4I',
    appId: '1:433434265166:ios:7238933b649e0c900ee51f',
    messagingSenderId: '433434265166',
    projectId: 'authentic-user-dashboard-app',
    storageBucket: 'authentic-user-dashboard-app.firebasestorage.app',
    iosBundleId: 'com.example.week5Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBee4S3pT06qWa6q5xONdQZPOH44_C4PzI',
    appId: '1:433434265166:web:4fee32bea772ed090ee51f',
    messagingSenderId: '433434265166',
    projectId: 'authentic-user-dashboard-app',
    authDomain: 'authentic-user-dashboard-app.firebaseapp.com',
    storageBucket: 'authentic-user-dashboard-app.firebasestorage.app',
    measurementId: 'G-6YS0QQCSZW',
  );
}
